#!/bin/bash

#Used directory

themes="Adapta-Maia Adapta-Nokto-Maia Adapta-Eta-Maia Adapta-Nokto-Eta-Maia"
gnomedir=/usr/share/gnome-shell
theme=gnome-shell-theme.gresource

#Remove GDM theme and icons

cd $gnomedir
if [ -f $theme.old ]; then
   rm $theme
   mv $theme.old $theme
else
   echo "Backup GDM theme not present"
fi

for i in $themes; do
	cd /usr/share/themes/$i/gnome-shell/assets
	rm show*.svg 
	for f in show*.old; do 
		mv -- "$f" "${f%.old}.svg"
	done
done

