#!/bin/bash

#Used directory
gnomedir=/usr/share/gnome-shell
themedir=/usr/share/themes/Adapta-Breath/gnome-shell
theme=gnome-shell-theme.gresource

#Install & Upgrade GDM theme

cd $gnomedir

install() {
mv $theme $theme.old
cp -f $themedir/$theme $gnomedir/$theme
}

upgrade() {
cmp --silent $gnomedir/$theme $themedir/$theme 
	if [ $? == 1 ]; then
		cp -f $themedir/$theme $gnomedir/$theme
	fi
}

if [ ! -e $theme.old ]; then
	install
else
	upgrade
fi

	

