#!/bin/bash

#Used directory
gnomedir=/usr/share/gnome-shell
themedir=/usr/share/themes/Adapta-Breath/gnome-shell
theme=gnome-shell-theme.gresource
appicondir=/usr/share/themes/Adapta-Breath/gnome-shell/assets

#Remove GDM theme and icons

cd $gnomedir
if [ -f $theme.old ]; then
   rm $theme
   mv $theme.old $theme
else
   echo "Backup GDM theme not present"
fi

cd $appincondir
for i in $(ls show*.old); do
	cp -f $i ${i::(-4)}
	rm $i
done

exit 0
