#!/bin/bash

#Used directory

gnomedir=/usr/share/gnome-shell
themedir=/usr/share/themes/manjaro-gdm-18.0-theme
theme=gnome-shell-theme.gresource

#Install & Upgrade GDM theme and icons

cd $gnomedir

install() {
#install gdm theme
cp -f $themedir/$theme $gnomedir/$theme
}

upgrade() {
cmp --silent $gnomedir/$theme $themedir/$theme 
	if [ $? == 1 ]; then
		cp -f $themedir/$theme $gnomedir/$theme
	fi
}

if [ ! -e $theme.old ]; then
	install
else
	upgrade
fi

