#!/bin/bash

#Used directory

theme="Adapta-Breath Adapta-Nokto-Breath Adapta-Eta-Breath Adapta-Nokto-Eta-Breath"
gnomedir=/usr/share/gnome-shell
theme=gnome-shell-theme.gresource

#Remove GDM theme and icons

cd $gnomedir
if [ -f $theme.old ]; then
   rm $theme
   mv $theme.old $theme
else
   echo "Backup GDM theme not present"
fi

for i in $theme; do
	cd /usr/share/themes/$i/gnome-shell/assets
	rm show*.svg 
	mv show*.old show*.svg
done
